# Include from hyprland.conf: source = ~/.config/quickshell/keybinds/hyprland.conf
bind = SUPER, SPACE, exec, ~/.config/quickshell/veyctl ipc drawer toggle
bind = SUPER, comma, exec, ~/.config/quickshell/veyctl ipc settings toggle
bind = SUPER, V, exec, ~/.config/quickshell/veyctl ipc clipboard toggle
bind = SUPER, N, exec, ~/.config/quickshell/veyctl ipc notifications toggle
bind = SUPER, X, exec, ~/.config/quickshell/veyctl ipc power toggle
bind = SUPER, C, exec, ~/.config/quickshell/veyctl ipc control-center toggle
bind = SUPER, T, exec, ~/.config/quickshell/veyctl ipc calendar toggle
bind = SUPER, M, exec, ~/.config/quickshell/veyctl ipc media toggle
bind = SUPER, W, exec, ~/.config/quickshell/veyctl ipc wifi toggle
bind = SUPER, B, exec, ~/.config/quickshell/veyctl ipc bluetooth toggle
bind = SUPER, L, exec, ~/.config/quickshell/veyctl ipc brightness toggle
bind = SUPER, K, exec, ~/.config/quickshell/veyctl ipc keyboard toggle
bind = SUPER, I, exec, ~/.config/quickshell/veyctl ipc system toggle
