# Include from hyprland.conf: source = ~/.config/quickshell/keybinds/hyprland.conf
bind = SUPER, SPACE, exec, ~/.config/quickshell/natonctl ipc drawer toggle
bind = SUPER, comma, exec, ~/.config/quickshell/natonctl ipc settings toggle
bind = SUPER, V, exec, ~/.config/quickshell/natonctl ipc clipboard toggle
bind = SUPER, N, exec, ~/.config/quickshell/natonctl ipc notifications toggle
bind = SUPER, X, exec, ~/.config/quickshell/natonctl ipc power toggle
bind = SUPER, C, exec, ~/.config/quickshell/natonctl ipc control-center toggle
bind = SUPER, T, exec, ~/.config/quickshell/natonctl ipc calendar toggle
bind = SUPER, M, exec, ~/.config/quickshell/natonctl ipc media toggle
bind = SUPER, W, exec, ~/.config/quickshell/natonctl ipc wifi toggle
bind = SUPER, B, exec, ~/.config/quickshell/natonctl ipc bluetooth toggle
bind = SUPER, L, exec, ~/.config/quickshell/natonctl ipc brightness toggle
bind = SUPER, K, exec, ~/.config/quickshell/natonctl ipc keyboard toggle
bind = SUPER, I, exec, ~/.config/quickshell/natonctl ipc system toggle
